#### 【 Numpy - Array 생성 】

In [2]:
## 모듈 로딩
import numpy as np

In [4]:
## =================================================
## 빈 array 객체 생성
## =================================================
a1 = np.empty((3,4))
print(a1)
a2=np.empty(2)
a2

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56597091e-307]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306]
 [1.29061142e-306 1.20162137e-306 1.86912451e-306 2.46154782e-312]]


array([0., 0.])

In [7]:
## 초기화 => 값 넣기
a1.fill(255)
a1

array([[255., 255., 255., 255.],
       [255., 255., 255., 255.],
       [255., 255., 255., 255.]])

In [12]:
## =================================================
## 0으로 채운 array 객체 생성
## =================================================
## -> float64 기본
a1 = np.zeros((2,3))
print(a1.dtype, a1, sep='\n')

## -> int8 설정
a1 = np.zeros((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## -> bool 설정
a1 = np.zeros((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[0. 0. 0.]
 [0. 0. 0.]]
int8
[[0 0 0]
 [0 0 0]]
bool
[[False False False]
 [False False False]]


In [13]:
## =================================================
## 1으로 채운 array 객체 생성
## =================================================
## -> float64 기본
a1 = np.ones((2,3))
print(a1.dtype, a1, sep='\n')

## -> int8 설정
a1 = np.ones((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## -> bool 설정
a1 = np.ones((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[1. 1. 1.]
 [1. 1. 1.]]
int8
[[1 1 1]
 [1 1 1]]
bool
[[ True  True  True]
 [ True  True  True]]
