#### 【 Numpy - Array 생성 】

In [4]:
## 모듈 로딩
import numpy as np      ## 이미지 데이터 저장 관련 모듈
import cv2              ## opencv 패키지

In [6]:
## =================================================
## Image ==> 로딩 : ndarray 데이터
## =================================================
## 이미지 파일
IMG_FILE = '../DATA/Image/blackpink.jpg'

## 이미지 데이터 로딩 : cv2.imread(이미지파일경로_문자열)
imgNP = cv2.imread(IMG_FILE)

## 이미지 로우 데이터 정보 출력
print(f'이미지 로우 데이터 정보 => {imgNP.shape}, {imgNP.ndim}D차원')

이미지 로우 데이터 정보 => (704, 1199, 3), 3D차원


- 이미지와 동일 형태/타입의 ndarray 객체 생성 
<hr>

In [7]:
imgNP

array([[[231, 233, 244],
        [231, 233, 244],
        [230, 232, 243],
        ...,
        [232, 234, 245],
        [232, 234, 245],
        [232, 234, 245]],

       [[230, 232, 243],
        [230, 232, 243],
        [230, 232, 243],
        ...,
        [232, 234, 245],
        [232, 234, 245],
        [232, 234, 245]],

       [[229, 231, 242],
        [229, 231, 242],
        [229, 231, 242],
        ...,
        [232, 234, 245],
        [232, 234, 245],
        [232, 234, 245]],

       ...,

       [[223, 225, 236],
        [222, 224, 235],
        [222, 224, 235],
        ...,
        [215, 217, 227],
        [214, 216, 226],
        [214, 216, 226]],

       [[224, 226, 237],
        [224, 226, 237],
        [223, 225, 236],
        ...,
        [215, 217, 227],
        [214, 216, 226],
        [214, 216, 226]],

       [[225, 227, 238],
        [224, 226, 237],
        [224, 226, 237],
        ...,
        [215, 217, 227],
        [214, 216, 226],
        [214, 216, 226]]

In [12]:
a = np.empty_like(imgNP)
b= np.zeros_like(imgNP)
c= np.ones_like(imgNP)
d= np.full_like(imgNP, 255)
a, a.shape

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], shape=(704, 1199, 3), dtype=uint8),
 (704, 1199, 3))

In [13]:
b, b.shape

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], shape=(704, 1199, 3), dtype=uint8),
 (704, 1199, 3))

In [14]:
c, c.shape

(array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        ...,
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], shape=(704, 1199, 3), dtype=uint8),
 (704, 1199, 3))

In [15]:
d, d.shape

(array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  