#### 【 Numpy - 범위내 데이터 활용 ndarray 생성 】

- numpy.random.rand() : 0 ~ 1사이의 무작위 수로 생성 / randn() : 표준정규분포(평균:0, 분산:1)를 따르는 무작위 수로 생성 
- numpy.arange() : 순차적인 값으로 생성
- numpy.linspace() : 시작값~마지막값까지 num 등분 
- numpy.logspace() : 로그화 해줌

In [2]:
## 모듈 로딩
import numpy as np      ## 이미지 데이터 저장 관련 모듈
import cv2              ## opencv 패키지

- 임의의 데이터 생성 및 형변환 
<hr>

In [ ]:
## numpy.random.rand
print(np.random.rand())
a = np.random.rand(2,3)
a

0.2987616598740441


array([[0.0738391 , 0.49185014, 0.06027506],
       [0.70787277, 0.46288376, 0.01405928]])

In [ ]:
## numpy.random.randn
print(np.random.randn())
b = np.random.randn(2,3)
b

-2.1964434822865155


array([[ 0.84992036, -0.11515027, -0.91002012],
       [-1.1902231 ,  0.30554764, -1.37985402]])

In [11]:
## arange
a = np.arange(5)
print(a, a.dtype, a.shape)

b = np.arange(5.0)
print(b, b.dtype, b.shape)

c = np.arange(3,9,2)
print(c, c.dtype, c.shape)

[0 1 2 3 4] int64 (5,)
[0. 1. 2. 3. 4.] float64 (5,)
[3 5 7] int64 (3,)


In [18]:
## linspace
arr1 = np.linspace(2,3, num=3)
arr2 = np.linspace(1,5, num=5, endpoint=False)
arr3 , step=np.linspace(1,5, num=5, retstep=True)

arr3, step

(array([1., 2., 3., 4., 5.]), np.float64(1.0))

In [ ]:
## logspace -> 상용로그화 해줌
arr1=np.logspace(2,3, num=2)
arr2=np.logspace(1,3, num=3, endpoint=False)
arr3=np.logspace(1,3, num=3, endpoint=True)

arr1, arr2, arr3

(array([ 100., 1000.]),
 array([ 10.        ,  46.41588834, 215.443469  ]),
 array([  10.,  100., 1000.]))