# work_1218 이서범 <hr>
- 55p ~ 87p

Numpy

In [1]:
import cv2

In [2]:
img = cv2.imread('../DATA/Image/4star.jpg')
print(type(img))
print(img.ndim)
print(img.shape)
print(img.size)
print(img.dtype)
print(img.itemsize) ## 1바이트임을 뜻함

<class 'numpy.ndarray'>
3
(211, 210, 3)
132930
uint8
1


3.1.3 값으로 생성

In [3]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4]
int64
(4,)


In [4]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [5]:
c = np.array([1,2,3.14,4])
print(c)
print(c.dtype)

[1.   2.   3.14 4.  ]
float64


In [6]:
d = np.array([1,2,3,4], dtype=np.float32)
print(d)
print(d.dtype)

[1. 2. 3. 4.]
float32


3.1.4 크기와 초기 값으로 생성

In [7]:
a = np.empty((2,3))
print(a)
print(a.dtype)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [7.56597091e-307 1.89146896e-307 7.56571288e-307]]
float64


In [8]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [9]:
b=np.zeros((2,3))
print(b)
print(b.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [10]:
b=np.zeros((2,3), dtype=np.int8)
print(b)
print(b.dtype)

[[0 0 0]
 [0 0 0]]
int8


In [11]:
c=np.ones((2,3), dtype=np.int16)
print(c)
print(c.dtype)

[[1 1 1]
 [1 1 1]]
int16


In [12]:
d = np.full((2,3,4), 255, dtype=np.uint8)
print(d)
print(d.dtype)

[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]
uint8


In [13]:
a=np.empty_like(img)
b=np.zeros_like(img)
c=np.ones_like(img)
d=np.full_like(img, 255)

print(a,b,c,d)

[[[ 80   1 182]
  [239 192   1]
  [  0   0  48]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]] [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

3.1.5 시퀀스와 난수로 생성

In [14]:
a=np.arange(5)
print(a, a.dtype, a.shape)

[0 1 2 3 4] int64 (5,)


In [15]:
b = np.arange(5.0)
print(b, b.dtype, b.shape)

[0. 1. 2. 3. 4.] float64 (5,)


In [16]:
c=np.arange(3,9,2)
print(c, c.dtype, c.shape)

[3 5 7] int64 (3,)


In [17]:
np.random.rand()

0.5225259774642909

In [18]:
np.random.randn()

-0.2541250951885561

In [19]:
np.random.rand(2,3)

array([[0.37292688, 0.30242468, 0.09024078],
       [0.52959267, 0.2671332 , 0.47823738]])

In [20]:
np.random.randn(2,3)

array([[ 0.18956104,  0.12854138,  0.46775895],
       [-1.09789533, -0.77150264,  2.52234061]])

3.1.6 dtype 변경

In [21]:
a=np.arange(5)
print(a, a.dtype, a.shape)

b = a.astype('float')
print(b, b.dtype)

[0 1 2 3 4] int64 (5,)
[0. 1. 2. 3. 4.] float64


In [22]:
print(a.dtype)
c = a.astype(np.float64)
print(c, c.dtype)

int64
[0. 1. 2. 3. 4.] float64


In [23]:
print(a.dtype)
d = np.uint8(a)
d

int64


array([0, 1, 2, 3, 4], dtype=uint8)

3.1.7 차원 변경

In [24]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
d = np.arange(100).reshape(2,-1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [28]:
e = np.arange(100).reshape(-1,5)
print(e, e.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] (20, 5)


In [29]:
f = np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
f.reshape(6,)

array([0., 0., 0., 0., 0., 0.])

In [31]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [32]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

In [33]:
g = np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

3.1.8 브로드캐스팅 연산

In [35]:
myList = list(range(10))
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
for i in range(len(myList)):
    myList[i] = myList[i] + 1

myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
a = np.arange(10)
print(a)
a + 1

[0 1 2 3 4 5 6 7 8 9]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
a = np.arange(5)
print(a)

print(a+5)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[0 1 2 3 4]
[5 6 7 8 9]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[ 0  1  4  9 16]


In [39]:
b = np.arange(6).reshape(2,-1)
print(b)
b*2

[[0 1 2]
 [3 4 5]]


array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [40]:
print(a)
a > 2

[0 1 2 3 4]


array([False, False, False,  True,  True])

In [41]:
a = np.arange(10,60,10)
b = np.arange(1,6)
print(a, b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[10 20 30 40 50] [1 2 3 4 5]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[       10       400     27000   2560000 312500000]


In [42]:
a = np.ones((2,3))
b=np.ones((3,2))
# a+b

In [43]:
print(a)
c=np.arange(3)
print(c)

a+c

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [44]:
d = np.arange(2)
# a + d

In [45]:
d = np.arange(2).reshape(2,1)
print(a, d, sep='\n')
a + d

[[1. 1. 1.]
 [1. 1. 1.]]
[[0]
 [1]]


array([[1., 1., 1.],
       [2., 2., 2.]])

3.1.9 인덱싱과 슬라이싱

In [46]:
a = np.arange(10)
print(a)
print(a[5])

b = np.arange(12).reshape(3,4)
print(b, b[1], b[1,2])

[0 1 2 3 4 5 6 7 8 9]
5
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [4 5 6 7] 6


In [47]:
print(a, a[5], b, sep='\n')
b[0] = 0
print(b)


[0 1 2 3 4 5 6 7 8 9]
5
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
b[1,2] = 99
print(b)

[[ 0  0  0  0]
 [ 4  5 99  7]
 [ 8  9 10 11]]


In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[2:5]

array([2, 3, 4])

In [51]:
a[5:]

array([5, 6, 7, 8, 9])

In [52]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
b[0:2, 1]

array([1, 5])

In [55]:
b[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [56]:
b[2, :]

array([ 8,  9, 10, 11])

In [57]:
b[:, 1]

array([1, 5, 9])

In [58]:
b[0:2, 1:3] = 0
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [59]:
print(b)
bb = b[0:2, 1:3]
print(bb)
bb[0] = 99
b

[[ 0  0  0  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]
[[0 0]
 [0 0]]


array([[ 0, 99, 99,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

3.1.10 팬시 인덱싱

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
a[[1,3]] ## 1번 인덱스 / 3번 인덱스

array([1, 3])

In [62]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [63]:
a = np.arange(10)
print(a)
b = a>5
b

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [64]:
a[b]

array([6, 7, 8, 9])

In [65]:
a[a>5]

array([6, 7, 8, 9])

In [66]:
a[a>5] = 1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [67]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
b[[0,2]] ## b[[행],[열]] -> 열 없어서 행만 가져옴

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [69]:
b[[0,2], [1,3]] ## [0,1] , [2,3] 으로 묶임

array([ 1, 11])

3.1.11 병합과 분리

In [70]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [71]:
b=np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [74]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [75]:
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [76]:
np.concatenate((a,b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [77]:
np.concatenate((a,b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [80]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,130,10).reshape(4,3)
print(a,b,sep='\n\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [81]:
c=np.stack((a,b),0)
c.shape

(2, 4, 3)

In [82]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [83]:
d=np.stack((a,b),1)
d.shape

(4, 2, 3)

In [84]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [85]:
e=np.stack((a,b),2)
e.shape

(4, 3, 2)

In [86]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [ ]:
ee=np.stack((a,b), -1) ## 마지막 축을 뜻함
ee.shape

(4, 3, 2)

In [88]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,[3,6]) ## [:3] / [3:6] / [6:]

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [92]:
np.hsplit(a,[3,6,9]) ## [:3] / [3:6] / [6:9] / [9:]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [94]:
np.split(a, 3, 0) ## 마지막은 axis

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [95]:
np.split(a,[3,6,9],0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [96]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
np.vsplit(b,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [99]:
np.split(b,2,0)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [100]:
np.hsplit(b, [1])

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [102]:
np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

3.1.12 검색

In [103]:
a=np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
np.where(a>15) # 인덱스 반환

(array([6, 7, 8, 9]),)

In [110]:
np.where(a>15, 1, 0) ## 큰값은  1 아닌값은 0


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [112]:
print(a)
np.where(a>15, 99, a)

[10 11 12 13 14 15 16 17 18 19]


array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [113]:
np.where(a>15, a, 0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [114]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [119]:
print(coords[0], coords[0].shape)
np.stack((coords[0], coords[1]), -1)

[1 2 2 2 2] (5,)


array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [120]:
z=np.array([0,1,2,0,1,2])
np.nonzero(z)

(array([1, 2, 4, 5]),)

In [121]:
zz=np.array([[0,1,2],[1,2,0],[2,0,1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [122]:
coords=np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [123]:
np.stack((coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [125]:
print(a)
np.nonzero(a>15)

[10 11 12 13 14 15 16 17 18 19]


(array([6, 7, 8, 9]),)

In [126]:
np.where(a>15)

(array([6, 7, 8, 9]),)

In [127]:
print(b)
np.nonzero(b>6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [128]:
np.where(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [129]:
t=np.array([True, True, True])
np.all(t)

np.True_

In [131]:
t[1] = False
t

array([ True, False,  True])

In [132]:
np.all(t)

np.False_

In [133]:
tt=np.array([[True,True], [False,True], [True,True]])
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [134]:
np.all(tt,0)

array([False,  True])

In [135]:
np.all(tt,1)

array([ True, False,  True])

In [136]:
a=np.arange(10)
b=np.arange(10)
print(a,b,sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [137]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
np.all(a==b)

np.True_

In [139]:
b[5]=-1

In [140]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [141]:
np.all(a==b)

np.False_

In [142]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

In [143]:
np.where(a!=b)

(array([5]),)

3.1.13 기초 통계 함수

In [144]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
np.sum(a)

np.int64(66)

In [146]:
np.sum(a,0)

array([12, 15, 18, 21])

In [147]:
np.sum(a,1)

array([ 6, 22, 38])

In [148]:
np.mean(a)

np.float64(5.5)

In [149]:
np.mean(a,0)

array([4., 5., 6., 7.])

In [150]:
np.mean(a,1)

array([1.5, 5.5, 9.5])

In [151]:
np.amin(a)

np.int64(0)

In [152]:
np.amin(a,0)

array([0, 1, 2, 3])

In [153]:
np.amin(a,1)

array([0, 4, 8])

In [154]:
np.amax(a)

np.int64(11)

In [155]:
np.amax(a,0)

array([ 8,  9, 10, 11])

In [156]:
np.amax(a,1)

array([ 3,  7, 11])

In [160]:
np.amin == np.min

False

In [161]:
np.max == np.amax

False