#### [ ndarray 객체 생성 ]

In [1]:
## 모듈 로딩
import numpy as np

In [3]:
## 함수 : numpy.ndarray()
## ---------------------------------
## numpy ndarray 객체 생성
nparray01 = np.array([1,2,3,4,5])

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = int64
[1 2 3 4 5]


In [ ]:
## 함수 : numpy.ndarray()
## ---------------------------------
## numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.array([1,2,3,4,5], dtype=np.int8)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 1
nparray01.dtype       = int8
[1 2 3 4 5]


In [ ]:
## numpy ndarray 객체 생성 : 다른 타입의 데이터가 섞인 경우 자동 형변환
nparray01 = np.array([1,2.,3,4,5])      ## 2. 실수 데이터 때문에 전체를 실수로 저장

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = float64
[1. 2. 3. 4. 5.]


In [11]:
## numpy ndarray 객체 생성 : 다른 타입의 데이터가 섞인 경우 자동 형변환
nparray01 = np.array([1,'2',3,4,5])      ## '2' 데이터 때문에 전체를 유니코드로 저장

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 84
nparray01.dtype       = <U21
['1' '2' '3' '4' '5']


In [13]:
## numpy ndarray 객체 생성 : 
nparray01 = np.array([[11,22],[33,44],[55,66]])      

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (3, 2)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = int64
[[11 22]
 [33 44]
 [55 66]]


In [17]:
## numpy ndarray 객체 생성 : 3행 2열
nparray01 = np.array((2,2))      

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2,)
nparray01.size        = 2
nparray01.itemsize    = 8
nparray01.dtype       = int64
[2 2]


In [ ]:
## ======================================
## 함수 : numpy.zeros(shape, 0) : [기본] float
## ======================================
nparray01 = np.zeros((5,))

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = float64
[0. 0. 0. 0. 0.]


In [ ]:
## ======================================
## 함수 : numpy.ones(shape, 0) : [기본] float
## ======================================
nparray01 = np.ones((2,3))

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = float64
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
## ======================================
## 함수 : numpy.full(shape, n) : [기본] float
## ======================================
nparray01 = np.full((2,3), 7)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = int64
[[7 7 7]
 [7 7 7]]


In [28]:
## ==================================================
## 함수 : numpy.zeros_like(ndarray객체) : [기본] float  : 입력 배열과 동일한 형태의 0으로 채워진 배열 생성
##       numpy.ones_like(ndarray객체) : [기본] float
## ==================================================
## numpy ndarray 객체 생성
a = np.array([11,22])
nparray01 = np.zeros_like(a)
nparray02 = np.ones_like(a)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

## ndarray 속성
print('type(nparray02)       =', type(nparray02))    
print('nparray02.shape       =', nparray02.shape)    
print('nparray02.size        =', nparray02.size)        ## 원소 개수
print('nparray02.itemsize    =', nparray02.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray02.dtype       =', nparray02.dtype)       ## 원소들의 타입
print(nparray02)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2,)
nparray01.size        = 2
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 0]
type(nparray02)       = <class 'numpy.ndarray'>
nparray02.shape       = (2,)
nparray02.size        = 2
nparray02.itemsize    = 8
nparray02.dtype       = int64
[1 1]


In [29]:
## ==================================================
## 함수 : numpy.arange([start,] stop [,step]) -> []는 생략할 수 있다는 의미
##       [기] start=0, step=1
## ==================================================
## numpy ndarray 객체 생성
nparray01 = np.arange(5)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)


type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 1 2 3 4]


In [ ]:
## =======================================================================
## 함수 : numpy.arange([start,] stop [,step]) -> []는 생략할 수 있다는 의미
##       [기] start=0, step=1
##       [범위] start <= ~ < stop
## =======================================================================
## numpy ndarray 객체 생성
nparray01 = np.arange(2,10,3)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)


type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (3,)
nparray01.size        = 3
nparray01.itemsize    = 8
nparray01.dtype       = int64
[2 5 8]


In [34]:
## =======================================================================
## 함수 : numpy.linspace(start, stop, num=50,
##                       endpoint=True, retstep=False)
##       1D ndarry float
##       [기] start <= ~ < stop 사이 num개 숫자 생성
## =======================================================================
## numpy ndarray 객체 생성
nparray01 = np.linspace(0,3,num=10)                      ## 0<= ~ <=3 범위에서 10개 숫자 생성
nparray01,step = np.linspace(0,3,num=10, retstep=True)   ## 숫자 사이 간격값 반환 (retstep True로 하면)

## 숫자 사이 간격값
print('step                  =', step)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)


step                  = 0.3333333333333333
type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (10,)
nparray01.size        = 10
nparray01.itemsize    = 8
nparray01.dtype       = float64
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [35]:
## ===================================================
## 함수 : numpy.empty(shape, dtype)
##       1D ndarray float
##       초기화 되지 않은/쓰레기 값의 배열 생성
## ===================================================
## numpy ndarray객체 생성
arr = np.empty((3,4))

## ndarray 속성
print('arr.shape       =', arr.shape)
print('arr.size        =', arr.size)        ## 원소 개수
print('arr.dtype       =', arr.dtype)       ## 원소들의 타입
print(arr)

arr.shape       = (3, 4)
arr.size        = 12
arr.dtype       = float64
[[1.08981097e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.89146896e-307 4.89172634e-033 1.63271407e+185 4.04370840e-037]
 [1.10549574e-046 1.77011422e-051 1.33712394e+165 2.33817526e-052]]
